################################################################################
# FastReflex E84 CM33 non-secure boot project
################################################################################

include ../common.mk

APPNAME=proj_cm33_ns
VERBOSE=

CORE=CM33
CORE_NAME=CM33_0

COMPONENTS+=NNLITE2 ML_TFLM ML_INT8x8
DISABLE_COMPONENTS=
SOURCES=
INCLUDES=
DEFINES=TF_LITE_STATIC_MEMORY
VFP_SELECT+=
CFLAGS+=
CXXFLAGS+=
ASFLAGS+=
LDFLAGS+=
LDLIBS+=
LINKER_SCRIPT=
PREBUILD=
POSTBUILD=

CY_APP_PATH=
CY_GETLIBS_SHARED_PATH=../..
CY_GETLIBS_SHARED_NAME=mtb_shared

include $(CY_TOOLS_DIR)/make/start.mk
