#ifndef FASTREFLEX_CONTRACT_H
#define FASTREFLEX_CONTRACT_H

#define FASTREFLEX_PROTOCOL_VERSION       (1u)
#define FASTREFLEX_MAX_PAYLOAD_BYTES      (6400u)
#define FASTREFLEX_MEMBER_COUNT           (3u)
#define FASTREFLEX_RAW_DIMENSION          (6u)
#define FASTREFLEX_FEATURE_DIMENSION      (80u)
#define FASTREFLEX_HISTORY_SAMPLES        (20u)
#define FASTREFLEX_WINDOW_ELEMENTS        (1600u)
#define FASTREFLEX_INPUT_SCALE            (0.03241445869207382f)

#endif
